spring:
  profiles:
    #运行的环境
    active: my-test
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    # Redis服务器地址
    host: 192.168.169.128
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 1
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password:
  jackson:
    serialization:
      write-dates-as-timestamps: true

